# Generated by Django 4.0.3 on 2022-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getDestinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
